import { faFlag, faBars, faSearch, faMoon, faSun, faBell, faGift, 
	faTasks, faUserTie, faCog, faCreditCard, faSpinner, faSignOutAlt, 
	faTachometerAlt, faChartLine, faBookOpen, faAdjust, faAudioDescription, faCheckCircle,
	faBug, faEllipsisH, faMailReplyAll, faCircleCheck, faGlassCheers, faUser, faTicket, faPlateWheat,
    faBook, faHistory, faMessage, faTools, faFolder, faCode, faCodeMerge, faCloud, faAngleDown, faAngleUp} from '@fortawesome/free-solid-svg-icons';


export default {
    'faFlag': faFlag,
    'faBars': faBars,
    'faSearch': faSearch,
    'faMoon': faMoon,
    'faSun': faSun,
    'faBell': faBell,
    'faGift': faGift,
    'faTasks': faTasks,
    'faUserTie': faUserTie,
    'faCog': faCog,
    'faCreditCard': faCreditCard,
    'faSpinner': faSpinner,
    'faSignOutAlt': faSignOutAlt,
    'faTachometerAlt': faTachometerAlt,
    'faChartLine': faChartLine,
    'faBookOpen': faBookOpen,
    'faAdjust': faAdjust,
    'faAudioDescription': faAudioDescription,
    'faCheckCircle': faCheckCircle, 
    'faBug': faBug,
    'faEllipsisH': faEllipsisH,
    'faMailReplyAll': faMailReplyAll,
    'faCircleCheck': faCircleCheck,
    'faGlassCheers': faGlassCheers,
    'faUser': faUser,
    'faTicket': faTicket,
    'faPlateWheat': faPlateWheat,
    'faBook': faBook,
    'faHistory': faHistory,
    'faMessage': faMessage,
    'faTools': faTools,
    'faFolder': faFolder,
    'faCode': faCode,
    'faCodeMerge': faCodeMerge,
    'faCloud': faCloud,
    'faAngleDown': faAngleDown,
    'faAngleUp': faAngleUp,
    }